name: Test Bats Unix
on: [pull_request]

concurrency:
  group: ci-bats-unix-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Bats tests
    defaults:
      run:
        shell: bash
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-22.04, macos-latest ]
    env:
      use_credentials: ${{ secrets.AWS_SECRET_ACCESS_KEY != '' && secrets.AWS_ACCESS_KEY_ID != '' }}
    steps:
      - name: Conditionally Set ENV VARS for AWS tests
        run: |
          if [[ $use_credentials == true ]]; then
            echo "AWS_SDK_LOAD_CONFIG=1" >> $GITHUB_ENV
            echo "AWS_REGION=us-west-2" >> $GITHUB_ENV
            echo "DOLT_BATS_AWS_TABLE=dolt-ci-bats-manifests-us-west-2" >> $GITHUB_ENV
            echo "DOLT_BATS_AWS_BUCKET=dolt-ci-bats-chunks-us-west-2" >> $GITHUB_ENV
            echo "DOLT_BATS_AWS_EXISTING_REPO=aws_remote_bats_tests__dolt__" >> $GITHUB_ENV
          fi
      - name: Configure AWS Credentials
        if: ${{ env.use_credentials == 'true' }}
        uses: aws-actions/configure-aws-credentials@v2.2.0
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          role-duration-seconds: 10800 # 3 hours D:
      - name: Setup Go 1.x
        uses: actions/setup-go@v3
        with:
          go-version: ^1.20
        id: go
      - name: Setup Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ^16
      - name: Create CI Bin
        run: |
          mkdir -p ./.ci_bin
          echo "$(pwd)/.ci_bin" >> $GITHUB_PATH
      - name: Verify Bats Naming Scheme
        run: ./check_bats_fmt.sh
        working-directory: ./testing/bats/setup
      - name: Install Bats
        run: |
          npm i bats
          echo "$(pwd)/node_modules/.bin" >> $GITHUB_PATH
        working-directory: ./.ci_bin
      - name: Install Python Deps
        run: |
          pip install mysql-connector-python
      - name: Install DoltgreSQL
        working-directory: ./
        run: |
          go build -mod=readonly -o .ci_bin/doltgresql .
      - name: Setup DoltgreSQL Config
        run: |
          doltgresql config --global --add user.name 'Dolthub Actions'
          doltgresql config --global --add user.email 'actions@dolthub.com'
      - name: Install PSQL Ubuntu
        if: matrix.os == 'ubuntu-22.04'
        run: |
          sudo sh -c 'echo "deb https://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
          wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
          sudo apt-get update
          sudo apt-get install --yes --no-install-recommends postgresql-client-15
      - name: Install PSQL MacOS
        if: matrix.os == 'macos-latest'
        run: |
          brew install postgresql@15
          brew link --overwrite postgresql@15
      - name: Test all Unix
        env:
          SQL_ENGINE: "local-engine"
          BATS_TEST_RETRIES: "3"
        run: |
          bats --tap .
        working-directory: ./testing/bats
