name: Static Analysis & Linter
on: [pull_request]

concurrency:
  group: ci-staticcheck-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    name: Run Staticcheck
    runs-on: ubuntu-22.04
    steps:
      - name: Setup Go 1.x
        uses: actions/setup-go@v3
        with:
          go-version: ^1.21
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Build SQL Syntax
        run: ./build.sh
        working-directory: ./postgres/parser
        shell: bash
      - name: Run check
        run: |
          go install honnef.co/go/tools/cmd/staticcheck@2023.1.6
          staticcheck ./...
