name: Test Replication
on: [pull_request]

concurrency:
  group: test-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    services:
      postgres:
        image: bitnami/postgresql:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRESQL_WAL_LEVEL: logical
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10
        ports:
          - 5432:5432
    steps:
    - name: Setup Go 1.x
      uses: actions/setup-go@v3
      with:
        go-version: ^1.21
      id: go
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Build SQL Syntax
      run: ./build.sh
      working-directory: ./postgres/parser
      shell: bash
    - name: Test
      run: go test -run="TestReplication" ./...
